# Generated by Django 5.1.3 on 2024-11-30 21:54

import django.db.models.deletion
import master_data.models.vendor_gallery
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=master_data.models.vendor_gallery.vendor_galleries)),
                ('deleted_flag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(blank=False, on_delete=django.db.models.deletion.PROTECT, to='master_data.vendor')),
            ],
            options={
                'db_table': 'vendor_gallery',
                'get_latest_by': ['-created_at'],
            },
        ),
    ]
