# Generated by Django 5.1.3 on 2024-11-30 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_vendorgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('deleted_flag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(blank=False, on_delete=django.db.models.deletion.PROTECT, to='master_data.vendor')),
            ],
            options={
                'db_table': 'vendor_package',
                'get_latest_by': ['-created_at'],
            },
        ),
    ]
