# Generated by Django 5.1.3 on 2024-12-01 16:25

import django.core.validators
import master_data.models.vendor
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_vendorschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='height_field',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='vendor',
            name='width_field',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='profile_image',
            field=models.ImageField(blank=True, height_field='height_field', upload_to=master_data.models.vendor.vendor_profile_images, validators=[
                                    django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], width_field='width_field'),
        ),
    ]
