# Generated by Django 5.1.3 on 2024-12-01 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0007_alter_vendorgallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorgallery',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='galleries', to='master_data.vendor'),
        ),
        migrations.AlterField(
            model_name='vendorpackage',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='master_data.vendor'),
        ),
        migrations.AlterField(
            model_name='vendorschedule',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='master_data.vendor'),
        ),
    ]
