# Generated by Django 5.1.3 on 2024-12-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_alter_vendor_facebook_alter_vendor_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='deleted_flag',
        ),
        migrations.AddField(
            model_name='vendor',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='transaction_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorschedule',
            name='day',
            field=models.CharField(choices=[('senin', 'Monday'), ('selasa', 'Tuesday'), ('rabu', 'Wednesday'),
                                   ('kamis', 'Thursday'), ('jumat', 'Friday'), ('sabtu', 'Saturday'), ('minggu', 'Sunday')]),
        ),
    ]
