# Generated by Django 5.1.3 on 2024-12-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0010_remove_vendor_deleted_flag_vendor_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorschedule',
            name='deleted_flag',
        ),
        migrations.AddField(
            model_name='vendorschedule',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorschedule',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorschedule',
            name='transaction_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
