# Generated by Django 5.1.3 on 2024-12-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0014_remove_vendorcategory_deleted_flag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'master_city',
                'get_latest_by': ['-created_at'],
            },
        ),
    ]
