# Generated by Django 5.1.3 on 2024-12-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0015_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorschedule',
            name='day',
            field=models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'),
                                   ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu'), ('Minggu', 'Minggu')]),
        ),
    ]
