# Generated by Django 5.1.3 on 2024-12-20 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0016_alter_vendorschedule_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='master_data.city'),
            preserve_default=False,
        ),
    ]
