# Generated by Django 5.1.3 on 2024-12-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0016_alter_vendorschedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorschedule',
            name='day',
            field=models.CharField(choices=[('MO', 'Senin'), ('TU', 'Selasa'), ('WE', 'Rabu'),
                                   ('TH', 'Kamis'), ('FR', 'Jumat'), ('SA', 'Sabtu'), ('SU', 'Minggu')]),
        ),
    ]
