# Generated by Django 5.1.3 on 2024-12-24 06:49
from typing import List, Dict

from django.db import migrations
from django.db.models import QuerySet

from backend.system_utility.system_constant import DAYS
from master_data.models.vendor_schedule import VendorSchedule

class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0017_alter_vendorschedule_day'),
    ]

    def migrate_schedule_days(self, schema_editor):

        all_schedule: QuerySet[VendorSchedule] = VendorSchedule.objects.all()
        modified_schedule: List[VendorSchedule] = []
        days_in_dict: Dict[str, str] = {}

        for a_tuple in DAYS:

            tup_key, tup_val = a_tuple
            days_in_dict[tup_val.lower()] = tup_key

        for a_schedule in all_schedule:

            a_schedule.day = days_in_dict[a_schedule.day]
            modified_schedule.append(a_schedule)

        VendorSchedule.objects.bulk_update(modified_schedule, ['day'])

    operations = [
        migrations.RunPython(migrate_schedule_days, migrations.RunPython.noop),
    ]
