# Generated by Django 5.1.3 on 2024-12-28 19:41

import django.core.validators
import django.db.models.deletion
import master_data.models.package_gallery
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0019_vendor_address_vendor_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=master_data.models.package_gallery.package_galleries, validators=[
                 django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='galleries', to='master_data.vendorpackage')),
            ],
            options={
                'db_table': 'package_gallery',
                'get_latest_by': ['-created_at'],
            },
        ),
    ]
