# Generated by Django 5.1.3 on 2024-12-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0020_packagegallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpackage',
            name='terms_and_condition',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendorpackage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
