# Generated by Django 5.1.3 on 2025-01-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0021_vendorpackage_terms_and_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorpackage',
            name='description',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
