# Generated by Django 5.1.3 on 2025-01-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0022_alter_vendorpackage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpackage',
            name='short_descriptions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorpackage',
            name='description',
            field=models.TextField(),
        ),
    ]
