# Generated by Django 5.1.3 on 2025-01-28 23:43

import uuid
from django.db import migrations, models


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("master_data", "Vendor")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0023_vendorpackage_short_descriptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='vendor',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
