# Generated by Django 5.1.3 on 2025-01-28 23:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0023_vendorpackage_short_descriptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
