# Generated by Django 5.1.3 on 2025-01-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0024_add_vendor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorschedule',
            name='vendor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vendorgallery',
            name='vendor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vendorpackage',
            name='vendor',
            field=models.IntegerField(),
        ),
    ]
