# Generated by Django 5.1.3 on 2025-01-28 23:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0025_populate_uuid_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
