# Generated by Django 5.1.3 on 2025-01-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0026_remove_uuid_null_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorschedule',
            name='vendor',
            field=models.IntegerField(),
        ),
    ]
