# Generated by Django 5.1.3 on 2025-01-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0026_alter_vendor_id_alter_vendor_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorgallery',
            old_name='vendor',
            new_name='vendor_old_id',
        ),
        migrations.RenameField(
            model_name='vendorpackage',
            old_name='vendor',
            new_name='vendor_old_id',
        ),
        migrations.RenameField(
            model_name='vendorschedule',
            old_name='vendor',
            new_name='vendor_old_id',
        ),
        migrations.AlterField(
            model_name='vendorschedule',
            name='vendor_old_id',
            field=models.IntegerField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='vendorgallery',
            name='vendor_old_id',
            field=models.IntegerField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='vendorpackage',
            name='vendor_old_id',
            field=models.IntegerField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='id',
            field=models.IntegerField(null=True, blank=True),
        ),
    ]
