# Generated by Django 5.1.3 on 2025-01-29 00:16

import django.db.models.deletion
from django.db import migrations, models


def copy_vendor_uuid(apps, schema_editor):
    VendorPackage = apps.get_model('master_data', 'VendorPackage')
    VendorGallery = apps.get_model('master_data', 'VendorGallery')
    VendorSchedule = apps.get_model('master_data', 'VendorSchedule')
    Vendor = apps.get_model('master_data', 'Vendor')
    vendor_uuid = Vendor.objects.filter(id=models.OuterRef('vendor_old_id')) \
        .values_list('uuid')[:1]
    VendorPackage.objects.update(vendor=models.Subquery(vendor_uuid))
    VendorGallery.objects.update(vendor=models.Subquery(vendor_uuid))
    VendorSchedule.objects.update(vendor=models.Subquery(vendor_uuid))


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0027_rename_vendor_vendorgallery_vendor_old_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpackage',
            name='vendor',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='packages',
                to='master_data.Vendor'
            ),
        ),
        migrations.AddField(
            model_name='vendorgallery',
            name='vendor',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='galleries',
                to='master_data.Vendor'
            ),
        ),
        migrations.AddField(
            model_name='vendorschedule',
            name='vendor',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='schedules',
                to='master_data.Vendor'
            ),
        ),
        migrations.RunPython(
            copy_vendor_uuid,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='vendorgallery',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='galleries', to='master_data.vendor'),
        ),
        migrations.AlterField(
            model_name='vendorpackage',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='master_data.vendor'),
        ),
        migrations.AlterField(
            model_name='vendorschedule',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='master_data.vendor'),
        ),
    ]
