# Generated by Django 5.1.3 on 2025-01-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0027_alter_vendorschedule_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorgallery',
            name='vendor',
            field=models.IntegerField(),
        ),
    ]
