# Generated by Django 5.1.3 on 2025-04-05 01:37

import uuid
from django.db import migrations, models

def gen_vendor_gallery_uuid(apps, schema_editor):
    MyModel = apps.get_model("master_data", "VendorGallery")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])

def gen_vendor_package_uuid(apps, schema_editor):
    MyModel = apps.get_model("master_data", "VendorPackage")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])

def gen_vendor_schedule_uuid(apps, schema_editor):
    MyModel = apps.get_model("master_data", "VendorSchedule")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])

class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0028_auto_20250129_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorgallery',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='vendorpackage',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='vendorschedule',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(gen_vendor_gallery_uuid, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(gen_vendor_package_uuid, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(gen_vendor_schedule_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='vendorgallery',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='vendorpackage',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='vendorschedule',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
