# Generated by Django 5.1.3 on 2025-01-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0028_alter_vendorgallery_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorpackage',
            name='vendor',
            field=models.IntegerField(),
        ),
    ]
