# Generated by Django 5.1.3 on 2025-04-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0029_vendorgallery_uuid_vendorpackage_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagegallery',
            name='package',
            field=models.IntegerField(null=True, blank=True),
        ),
    ]
