# Generated by Django 5.1.3 on 2025-01-29 00:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0029_alter_vendorpackages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
