# Generated by Django 5.1.3 on 2025-04-05 01:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0030_alter_packagegallery_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorgallery',
            name='id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vendorgallery',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='vendorpackage',
            name='id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vendorpackage',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='vendorschedule',
            name='id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vendorschedule',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
