# Generated by Django 5.1.3 on 2025-01-29 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0030_alter_vendor_id_alter_vendor_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorgallery',
            old_name='vendor',
            new_name='vendor_old',
        ),
        migrations.RenameField(
            model_name='vendorpackage',
            old_name='vendor',
            new_name='vendor_old',
        ),
        migrations.RenameField(
            model_name='vendorschedule',
            old_name='vendor',
            new_name='vendor_old',
        ),
    ]
