# Generated by Django 5.1.3 on 2025-04-05 01:58

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0031_alter_vendorgallery_id_alter_vendorgallery_uuid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagegallery',
            old_name='package',
            new_name='package_old_id',
        ),
        migrations.AlterField(
            model_name='packagegallery',
            name='package_old_id',
            field=models.IntegerField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='vendorschedule',
            name='id',
            field=models.IntegerField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='vendorgallery',
            name='id',
            field=models.IntegerField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='vendorpackage',
            name='id',
            field=models.IntegerField(null=True, blank=True),
        ),
    ]
