# Generated by Django 5.1.3 on 2025-01-29 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0032_auto_20250129_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vendorgallery',
            name='vendor_old',
        ),
        migrations.RemoveField(
            model_name='vendorpackage',
            name='vendor_old',
        ),
        migrations.RemoveField(
            model_name='vendorschedule',
            name='vendor_old',
        ),
        migrations.AlterField(
            model_name='vendorgallery',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='galleries', to='master_data.vendor'),
        ),
        migrations.AlterField(
            model_name='vendorpackage',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='master_data.vendor'),
        ),
        migrations.AlterField(
            model_name='vendorschedule',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='master_data.vendor'),
        ),
    ]
