# Generated by Django 5.1.3 on 2025-01-29 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0033_remove_vendor_id_remove_vendorgallery_vendor_old_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='uuid',
            new_name='id',
        ),
    ]
