# Generated by Django 5.1.3 on 2025-04-05 02:25

import uuid
from django.db import migrations, models

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("master_data", "PackageGallery")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])

class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0033_packagegallery_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagegallery',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='packagegallery',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),

    ]
