# Generated by Django 5.1.3 on 2025-01-29 00:58

import uuid
from django.db import migrations, models


def create_uuid(apps, schema_editor):
    VendorPackage = apps.get_model('master_data', 'VendorPackage')
    for vp in VendorPackage.objects.all():
        vp.uuid = uuid.uuid4()
        vp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0034_rename_uuid_vendor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpackage',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(create_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='vendorpackage',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
