# Generated by Django 5.1.3 on 2025-04-05 02:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0034_packagegallery_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagegallery',
            name='id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='packagegallery',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
