# Generated by Django 5.1.3 on 2025-01-29 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0035_vendorpackage_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagegallery',
            name='package',
            field=models.IntegerField(),
        ),
    ]
