# Generated by Django 5.1.3 on 2025-04-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0035_alter_packagegallery_id_alter_packagegallery_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagegallery',
            name='id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
