# Generated by Django 5.1.3 on 2025-01-29 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0037_alter_vendorpackage_id_alter_vendorpackage_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagegallery',
            old_name='package',
            new_name='package_old',
        ),
    ]
