# Generated by Django 5.1.3 on 2025-01-29 01:04
import django.db.models.deletion
from django.db import migrations, models


def copy_vendor_package_uuid(apps, schema_editor):
    PackageGallery = apps.get_model('master_data', 'PackageGallery')
    VendorPackage = apps.get_model('master_data', 'VendorPackage')
    vendor_package_uuid = VendorPackage.objects.filter(id=models.OuterRef('package_old')) \
        .values_list('uuid')[:1]
    PackageGallery.objects.update(package=models.Subquery(vendor_package_uuid))


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0038_rename_package_packagegallery_package_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagegallery',
            name='package',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='galleries',
                to='master_data.vendorpackage'
            ),
        ),
        migrations.RunPython(
            copy_vendor_package_uuid,
            reverse_code=migrations.RunPython.noop
        ),
    ]
