# Generated by Django 5.1.3 on 2025-01-29 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0039_auto_20250129_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagegallery',
            name='package_old',
        ),
        migrations.RemoveField(
            model_name='vendorpackage',
            name='id',
        ),
        migrations.AlterField(
            model_name='packagegallery',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='galleries', to='master_data.vendorpackage'),
        ),
    ]
