# Generated by Django 5.1.3 on 2025-01-29 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0040_remove_packagegallery_package_old_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorpackage',
            old_name='uuid',
            new_name='id',
        ),
    ]
